import type { BuiltinAppId } from './types.ts'

/**
 * 内置应用显示名（无 React / CSS）。
 * 供 app-catalog、Worker 等路径使用；{@link APP_REGISTRY} 应与此保持一致。
 */
export const BUILTIN_APP_DISPLAY_NAMES: Record<BuiltinAppId, string> = {
  appstore: '应用集市',
  browser: '网页浏览器',
  chromo: 'Chromo',
  'page-devtools': '开发者工具',
  webview: 'WebView',
  mail: '邮件',
  news: '新闻',
  books: '书架',
  music: '音乐',
  weather: '天气',
  calendar: '月历',
  stocks: '股票',
  translate: '翻译',
  catgpt: 'CatGPT',
  produde: 'ProDude',
  gomoku: '五子棋',
  speech: '语音实验室',
  files: '文件',
  'file-info': '文件信息',
  textedit: '文本编辑',
  pages: '文稿',
  preview: '预览',
  vscode: 'Virtual Studio Code Desktop',
  'scene3d-lab': '3D 实验室',
  'model-vision': '模型识图',
  icode: 'iCode',
  registry: '注册表',
  settings: '系统设置',
  'system-info': '系统信息',
  'task-manager': '性能监视器',
  services: '服务',
  'event-log': '事件日志',
  packages: '包管理',
  'archive-utility': '压缩包实用工具',
  'space-sniffer': '空间嗅探',
  keychain: '钥匙串',
  'github-desktop': 'GitHub Desktop',
  help: '帮助',
  terminal: '终端',
  'simulated-terminal': '模拟终端',
  'virtual-js': 'Virtual JS',
  'ui-kit': 'UI 组件库',
  stems: '音乐实验室',
  'srml-demo': 'SRML 演示',
  'midi-demo': 'MIDI 演示',
  'llm-playground': 'LLM Playground',
  attunebench: '评测',
  welcome: '欢迎中心',
  'welcome-next': '欢迎',
  'welcome-hello': '你好',
}

export function isBuiltinAppId(appId: string): appId is BuiltinAppId {
  return Object.prototype.hasOwnProperty.call(BUILTIN_APP_DISPLAY_NAMES, appId)
}

/** 目录枚举顺序（与历史 APP_REGISTRY 顺序一致，便于对照；catalog 最终仍会按 bundleName 排序）。 */
export const BUILTIN_APP_CATALOG_ORDER: readonly BuiltinAppId[] = [
  'appstore',
  'browser',
  'chromo',
  'page-devtools',
  'webview',
  'mail',
  'news',
  'books',
  'music',
  'weather',
  'calendar',
  'stocks',
  'translate',
  'catgpt',
  'produde',
  'gomoku',
  'speech',
  'files',
  'file-info',
  'textedit',
  'pages',
  'preview',
  'vscode',
  'scene3d-lab',
  'model-vision',
  'icode',
  'registry',
  'settings',
  'system-info',
  'task-manager',
  'services',
  'event-log',
  'packages',
  'archive-utility',
  'space-sniffer',
  'keychain',
  'github-desktop',
  'help',
  'terminal',
  'simulated-terminal',
  'virtual-js',
  'ui-kit',
  'stems',
  'srml-demo',
  'midi-demo',
  'llm-playground',
  'attunebench',
  'welcome',
  'welcome-next',
  'welcome-hello',
]
