/** Re-export page-host config (Chromo-compatible names). */
export {
  PAGE_WORKER_ORIGIN,
  CHROMO_WORKER_ORIGIN,
  PAGE_VIEWER_URL,
  CHROMO_VIEWER_URL,
  PAGE_BLANK_PATH,
  CHROMO_BLANK_PATH,
  PAGE_DEFAULT_NEW_TAB_URL,
  CHROMO_DEFAULT_NEW_TAB_URL,
  PAGE_OMNIBOX_PLACEHOLDER,
  CHROMO_OMNIBOX_PLACEHOLDER,
  PAGE_DEFAULT_RPC_TIMEOUT,
  CHROMO_DEFAULT_RPC_TIMEOUT,
  PAGE_DEFAULT_SCREENSHOT_TIMEOUT,
  CHROMO_DEFAULT_SCREENSHOT_TIMEOUT,
} from '../../page-host/page-host-config.ts'
