/**
 * gen-boxvnt-modes —— boxvnt 静态模式表「密阶梯」段的单一事实源。
 *
 * 背景（todo/vm-arbitrary-resolution/00-overview.md §2 / R1 回退）：
 * XP 的 win32k 可能缓存 miniport 的模式列表（ReactOS 实现每次枚举都重建，
 * XP 真身未实证）。动态注入（宿主 IO 端口）是精确路径；密阶梯是兜底——
 * 即使列表被缓存，任何视口目标都能吸附到 ≤4px 误差的既有档位。
 *
 * 生成规则：
 *   - 宽度 640→2560、步长 8（与驱动 vmpValidateMode 的 HorzRes % 8 校验、
 *     宿主 resolution-channel 的 8px 网格取整三方对齐）；
 *   - 每宽度 × 常见纵横比 {4:3, 16:10, 16:9, 3:2}，高度四舍五入后夹进
 *     [480, 1600]；
 *   - 只生成 32bpp（XP 实际使用的深度；8/15/16/24 由上游 19 档基础表覆盖）；
 *   - 与基础表重复的分辨率不重复生成。
 *
 * 用法：
 *   node --experimental-strip-types scripts/gen-boxvnt-modes.ts           # 重写 vidmpdat.c 阶梯段
 *   node --experimental-strip-types scripts/gen-boxvnt-modes.ts --check   # 只校验无漂移（CI/单测用）
 *
 * 产物 B/C（宿主期望表、统计）不落盘：单测直接 import 本模块做断言，
 * 避免多一份需要对齐的生成物。
 */

import { readFileSync, writeFileSync } from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'

/** 与驱动侧 vmpValidateMode / dispi 上限一致。 */
export const LADDER_MIN_WIDTH = 640
export const LADDER_MAX_WIDTH = 2560
export const LADDER_MIN_HEIGHT = 480
export const LADDER_MAX_HEIGHT = 1600
export const LADDER_STEP = 8
export const LADDER_BPP = 32

/** 常见纵横比（宽:高）。 */
export const LADDER_ASPECTS: ReadonlyArray<readonly [number, number]> = [
  [4, 3],
  [16, 10],
  [16, 9],
  [3, 2],
]

/** vidmpdat.c 上游 19 档基础分辨率（各 5 个色深，此处只关心分辨率去重）。 */
export const BOXVNT_BASE_RESOLUTIONS: ReadonlyArray<readonly [number, number]> = [
  [640, 480],
  [800, 600],
  [1024, 768],
  [1152, 864],
  [1280, 720],
  [1280, 800],
  [1280, 960],
  [1360, 768],
  [1360, 1024],
  [1366, 768],
  [1400, 1050],
  [1440, 900],
  [1600, 1200],
  [1680, 1050],
  [1920, 1080],
  [1920, 1200],
  [2048, 1152],
  [2048, 1536],
  [2560, 1600],
]

export type LadderMode = {
  width: number
  height: number
  bpp: number
}

/** 生成完整密阶梯（已排序、去重、剔除基础表重复项）。 */
export function generateLadderModes(): LadderMode[] {
  const seen = new Set(
    BOXVNT_BASE_RESOLUTIONS.map(([w, h]) => `${w}x${h}`),
  )
  const modes: LadderMode[] = []
  for (let width = LADDER_MIN_WIDTH; width <= LADDER_MAX_WIDTH; width += LADDER_STEP) {
    for (const [aw, ah] of LADDER_ASPECTS) {
      const height = Math.round((width * ah) / aw)
      if (height < LADDER_MIN_HEIGHT || height > LADDER_MAX_HEIGHT) {
        continue
      }
      const key = `${width}x${height}`
      if (seen.has(key)) {
        continue
      }
      seen.add(key)
      modes.push({ width, height, bpp: LADDER_BPP })
    }
  }
  modes.sort((a, b) => a.width - b.width || a.height - b.height)
  return modes
}

/** 阶梯的 C 数组片段（不含标记行本身）。 */
export function formatLadderCFragment(modes: LadderMode[]): string {
  return modes
    .map((m) => `    { ${String(m.width).padStart(4)}, ${String(m.height).padStart(4)}, ${m.bpp} },`)
    .join('\n')
}

/** 阶梯最大显存需求（字节）；2560×1600×32 == 16,384,000B ≤ 16MB。 */
export function ladderMaxFramebufferBytes(modes: LadderMode[]): number {
  return modes.reduce((max, m) => Math.max(max, m.width * m.height * 4), 0)
}

const BEGIN_MARK = '/*Instant VM: dense-mode-ladder begin (generated by scripts/gen-boxvnt-modes.ts)*/'
const END_MARK = '/*Instant VM: dense-mode-ladder end*/'

export const VIDMPDAT_PATH = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../src/apps/virtual-machine/guest/boxvnt/vidmpdat.c',
)

/** 把 vidmpdat.c 的阶梯段替换为当前生成结果；返回是否发生写入。 */
export function regenerateVidmpdatLadder(filePath = VIDMPDAT_PATH): boolean {
  const source = readFileSync(filePath, 'utf8')
  const begin = source.indexOf(BEGIN_MARK)
  const end = source.indexOf(END_MARK)
  if (begin < 0 || end < 0 || end < begin) {
    throw new Error(`vidmpdat.c 缺少生成段标记：${filePath}`)
  }
  const next =
    source.slice(0, begin) +
    BEGIN_MARK +
    '\n' +
    formatLadderCFragment(generateLadderModes()) +
    '\n' +
    source.slice(end)
  if (next === source) {
    return false
  }
  writeFileSync(filePath, next)
  return true
}

/** 从 vidmpdat.c 提取阶梯段条目（供漂移断言）。 */
export function parseVidmpdatLadder(filePath = VIDMPDAT_PATH): LadderMode[] {
  const source = readFileSync(filePath, 'utf8')
  const begin = source.indexOf(BEGIN_MARK)
  const end = source.indexOf(END_MARK)
  if (begin < 0 || end < 0 || end < begin) {
    throw new Error(`vidmpdat.c 缺少生成段标记：${filePath}`)
  }
  const body = source.slice(begin + BEGIN_MARK.length, end)
  const modes: LadderMode[] = []
  for (const line of body.split('\n')) {
    const match = line.match(/^\s*\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\},?\s*$/)
    if (match) {
      modes.push({ width: Number(match[1]), height: Number(match[2]), bpp: Number(match[3]) })
    }
  }
  return modes
}

const isCli = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
if (isCli) {
  const checkOnly = process.argv.includes('--check')
  const modes = generateLadderModes()
  const maxBytes = ladderMaxFramebufferBytes(modes)
  if (checkOnly) {
    const inTree = parseVidmpdatLadder()
    const drift =
      inTree.length !== modes.length ||
      inTree.some((m, i) => m.width !== modes[i].width || m.height !== modes[i].height || m.bpp !== modes[i].bpp)
    if (drift) {
      console.error('vidmpdat.c 阶梯段与生成器输出不一致，请运行 gen-boxvnt-modes.ts 重新生成')
      process.exit(1)
    }
    console.log(`gen-boxvnt-modes --check ok (${modes.length} modes)`)
  } else {
    const wrote = regenerateVidmpdatLadder()
    console.log(
      `${wrote ? 'rewrote' : 'unchanged'} ${path.relative(process.cwd(), VIDMPDAT_PATH)}: ` +
        `${modes.length} ladder modes, max framebuffer ${Math.round(maxBytes / 1024 / 102.4) / 10} MiB`,
    )
  }
}
